### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'WSGIHandler' and 'str'

### ISSUE THREAD

**Issue by sethlivingston** [rmohr/static3#1]
I get the following error when I attempt to run a python3-django1.5-gunicorn-static3 application.

```
Traceback (most recent call last):
  File "/home/seth/virtualenv/pnp/lib/python3.3/site-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/seth/virtualenv/pnp/lib/python3.3/site-packages/static.py", line 139, in __call__
    full_path = self._full_path(path_info)
  File "/home/seth/virtualenv/pnp/lib/python3.3/site-packages/static.py", line 178, in _full_path
    return self.root + path_info
TypeError: unsupported operand type(s) for +: 'WSGIHandler' and 'str'
```

I get the same error when I run it

Locally:

```
gunicorn pnp.wsgi:application
```

Locally using foreman:

```
foreman start
```

And remotely on Heroku.

**Comment by joaopaulopires** [comment]
Hoje, 18/01/2022 tive o mesmo erro . E o problema era na importação da lib dj-static
estava fazendo: from static import Cling
e o correto é: from dj-static import Cling

Today, 01/18/2022 I activate the same error. And the problem was in the import of the dj-static lib
was doing: from static import Cling
and the correct one is: from dj-static import Cling
